spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bambooogre@gmail.com
    password: akjmcgxlsccehzmj
    properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true